### ISSUE TITLE
Event Code & Event Description

### ISSUE THREAD

**Issue by skoobiedoo** [aguinane/nem-reader#10]
Hi I'm pretty new to python and your module but is it possible to read the event_code & event_description from NMI? As we have 300 codes that have these in the RAW file but for the life of me I can't figure out the best way of getting these out to pull them into my CSV file.

**Comment by aguinane** [comment]
Yep the events come through in the record object, but not in the export to csv. 
Should be possible to add it.

**Comment by skoobiedoo** [comment]
I don't spose you have an example of how to read that in from a 300 record?

**Comment by skoobiedoo** [comment]
Not sure if I'm 100% right but it appears your code expects that there will be a 400 record whereas I've found a lot of the time there is a 300 record with event_code & event_description but no proceeding 400 record.

**Comment by aguinane** [comment]
It shouldn't expect a 400 row as most times they are just actual reads with no events.
Look at modifying the outputs.py file to include events - I can add it myself but might not be for a bit.

**Comment by skoobiedoo** [comment]
I'm not sure im doing it right as I've tried doing this with your outputs.py though this brick wall and my head are thinking of changing their facebook status to 'its complicated' :) any help no matter how quickly would be greatly appreciated! :) As the mod that I did to your output.py file the event_code & event_description keeps coming out empty :(

**Comment by aguinane** [comment]
The CSV output should include events now (in develop branch)

**Comment by skoobiedoo** [comment]
Thankyou so much for doing that. I was surprised how similar our code was for doing that but unfortunately because it was almost word for word I get the same result with yours :( event_code & event_desc are empty.  I had been looking over the nem_reader.py file and it seems that 'parse_interval_records' sets both those variables to '' on a 300 record.  Except in our files sometimes the 300 record if the quality method isn't 'A' it has this after it '76,Communications fault' as an example.  Though I don't seem to be able to read that out of the file.

**Comment by aguinane** [comment]
Can you supply an example file where it's not working? 
I tested on the AEMO example files and it worked.

**Comment by skoobiedoo** [comment]
> Can you supply an example file where it's not working? I tested on the AEMO example files and it worked.

Silly question how do I send you the file and not post it publicly?

**Comment by skoobiedoo** [comment]
Sure here is the file.
[filetest.txt](https://github.com/aguinane/nem-reader/files/3408962/filetest.txt)

**Comment by aguinane** [comment]
Ah, you were right. It does assume that reason codes will not exist if there is no 400 record.
That's because in most cases the event won't exist for the whole day (but in your example it does).
The reason_code and reason_description is being read when the 300 row is parsed - but these values are not getting sent to the parse_interval_records function. 

Adding these as arguments to the parse_interval_records function will fix that - will try to fix up the code over the weekend.

**Comment by skoobiedoo** [comment]
Aw if you can fix that you are my new hero! :) I never call things bugs I prefer the term 'an undocumented feature' :)

**Comment by aguinane** [comment]
Just pushed a fix.
