### ISSUE TITLE
parse_200_row throws list index out of range

### ISSUE THREAD

**Issue by perrin7** [aguinane/nem-reader#13]
How to reproduce error:
```
import nemreader as nr
nr.read_nem_file("no_comma.csv")
```
**working example**
```
import nemreader as nr
nr.read_nem_file("with_comma.csv")
```
See attached NEM12 files:
[test_nem12_files.zip](https://github.com/aguinane/nem-reader/files/3582404/test_nem12_files.zip)

Per the NEM12 standard, the 9th item in the 200 row "NextScheduledReadDate" is not mandatory, so it cannot be assumed that it will exist.
```
def parse_200_row(row: list) -> NmiDetails:
    """ Parse NMI data details record (200) """
    return NmiDetails(
        row[1],
        row[2],
        row[3],
        row[4],
        row[5],
        row[6],
        row[7],
        int(row[8]),
        parse_datetime(row[9]),  # This is non-mandatory!
    )
```

**Comment by aguinane** [comment]
Fixed with 2c79856

**Comment by perrin7** [comment]
Thanks for fixing this!  Any chance it will make it into the master branch?

**Comment by aguinane** [comment]
Pushed new version to pip
