### ISSUE TITLE
Handle missing 100 record

### ISSUE THREAD

**Issue by dwjp** [aguinane/nem-reader#16]
Despite being mandatory, I often see NEM12 files where the 100 header record is skipped (particularly for interval data from Powercor/Citipower portals).

Looking through `nem_reader.py` it appears parsing will raise an exception if this is the case?

Would be useful to have an option to ignore this, or catch and decide whether to continue on case-by-case basis.

**Comment by aguinane** [comment]
Should be easy enough to add an option to generate a warning instead of an error with a flag and then assume that it's NEM12 and not NEM13 and continue. Will add it when I get time otherwise feel free to submit a PR.

**Comment by dwjp** [comment]
Thanks, will submit a PR when I get a free moment. I have some other weird out-of-spec NEM12 files to work through so suspect it'll raise some other issues to work through.

**Comment by lyricnz** [comment]
How is this closed?  Still getting

ValueError: NEM Files must start with a 100 row

On a CSV file downloaded from United Energy:

```
200,xxx,5,E1E2,E1,E1,,yyy,KWH,30,
300,20200914,.362,.338,.313,.394,.45,.431,.431,.525,1.219,.463,.569,.569,.531,.637,.938,.556,.625,1.331,1.369,1.219,1.725,.75,.281,.306,.375,.356,.294,.338,.369,.35,.338,.325,.431,.237,.269,.869,.444,1.469,1.381,1.006,.906,.263,.237,.256,.988,.125,.113,.163,A,,,20200915012258,
300,20200915,.156,.1,.113,.169,.156,.113,.106,.875,.263,.156,.1,.106,.163,.2,1.519,1.869,1.663,2.275,2.256,2.3,2.35,1.231,1.163,1.462,1.35,.481,1.375,.444,.919,1.163,1.156,1.138,2.644,2.013,1.369,.369,.287,1.619,2.656,1.063,1.094,.344,.325,.263,.281,.231,.194,.794,A,,,20200916011825,
```

**Comment by aguinane** [comment]
Yeah should probably be added to documentation, and probably default to True when using the CLI maybe?

**Comment by aguinane** [comment]
Making some changes for another issue and changed this to a `strict` option that is False by default.
