### ISSUE TITLE
Handle Powercor/Citipower idiosyncrasies

### ISSUE THREAD

**Issue by dwjp** [aguinane/nem-reader#17]
Working with data from the Powercor customer portal... I've no idea if these quirks exist across their other systems.

Aside from missing 100 row (#16), also see:

- Blank row at start
- Multiple 900 rows, followed by a blank row, then more data (i.e. from another register)!

Should be easy enough to work around, but not sure on preferred general approach? i.e. Strict NEM12 by default, and incremental options to allow variations, dialects like `csv` module, or just try and intelligently figure out as much as possible, automatically.

I should be able to anonymise some data for test cases, if need be.

**Comment by aguinane** [comment]
Yeah some test cases would be good. You could also break some of the existing examples in the same way if you don't want to use real examples. Probably better to handle issues automatically, as long as it doesn't impact any correct files (which should be covered by existing unit tests).

**Comment by dwjp** [comment]
Noticed another quirk where there can be empty rows, but not blank (i.e. `len(row) > 0`, but each element is empty)... will modify to catch that too.

**Comment by aguinane** [comment]
Closing this one - note I changed how this is done in the latest version. There is now a strict option that defaults to False.
