### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by jayvdb** [aguinane/nem-reader#23]
https://files.pythonhosted.org/packages/source/n/nemreader/nemreader-0.5.2.tar.gz

setup.py opens requirements.txt, which isnt in the sdist, so it fails.

I suspect the same problem exists in nemwriter.

**Comment by aguinane** [comment]
Ah, I've been installing the wheel so was working fine for me.
If I run ```pip install nemreader --no-binary=:all:``` I do get the error.
I'll go back to hardcoding the requirements in the setup.py.

**Comment by aguinane** [comment]
Should be fixed by a1eda63

**Comment by aguinane** [comment]
This is now fixed.
