### ISSUE TITLE
Program Execution Issues - Beginner

### ISSUE THREAD

**Issue by futzy-r** [aguinane/nem-reader#26]
Hi,
First, a big thank you to the authors for developing this much needed application; 
I am new to Python and have trouble in running the code; 

I have installed nem_reader but not sure on how to execute the program. 

PS: I have installed the Eclipse platform with Pydev and need help to run the programs; 

thank you.

**Comment by aguinane** [comment]
What are you trying to do?
It's not a program really but a library, so requires you write some of your own python code to get it to work.
You can run it from the command line if you simply want to convert NEM12 to a transposed CSV.

**Comment by futzy-r** [comment]
Hi Alex,
Thank you for your guidance. I am trying to analyse the NEM2 example interval data to plot the time series data and understand the peaks in the energy demands. 

Is there sample code that you can share?
Regards 
Anup

**Comment by aguinane** [comment]
Here is some sample code:
https://nem-reader.readthedocs.io/en/latest/quickstart.html#

**Comment by aguinane** [comment]
Closing old issue.
