### ISSUE TITLE
Different registers have the wrong date

### ISSUE THREAD

**Issue by rob-ioenegy** [aguinane/nem-reader#28]
Firstly thanks for creating this library.

I've noticed an issue with a NEM12 file which contains three registers, E2E1B1, being controlled load, main load, solar export, in that order.

The E2 and E1 registers Start on 2019/12/25 and end on 2021/08/19; while the B1 register does not start until 2020/01/24 (when the solar system was installed).

When I run nemreader output "NMI_From_To_SAPN_DETAILED.csv" in terminal

I get:
Created NMI1234561_20210820_transposed.csv

It transposes the data,  but instead of returning zeros or NaN for the B1 register from 2019/12/25 to 2020/01/23; it instead as the B1 data starting on the same date as the E2 E1 registers.

See attached original NEM12 file (anonymised) and the transposed file output.
[NMI1234561_20210820_transposed.csv](https://github.com/aguinane/nem-reader/files/7063222/NMI1234561_20210820_transposed.csv)
[NMI_From_To_SAPN_DETAILED.csv](https://github.com/aguinane/nem-reader/files/7063223/NMI_From_To_SAPN_DETAILED.csv)

Thanks, Rob

**Comment by aguinane** [comment]
I think this should be fixed by 590a20656ed6410c237adce5b156d58497c69771
