### ISSUE TITLE
Separate NEM12 and NEM12 Parsers

### ISSUE THREAD

**Issue by benjamin-croker** [aguinane/nem-reader#3]
Despite similarities, these parsers should possibly be seperate. They have different blocking (i.e. parsing flow) diagrams, and organise their data differently.

**Comment by aguinane** [comment]
Maybe different functions that you call, but I'd want the returned objects to be the same.

**Comment by benjamin-croker** [comment]
From the user's perspective it would be the same. The interface would read the first row of the file, then call the correct parser.

**Comment by aguinane** [comment]
Seperated in 06a6ccb
