### ISSUE TITLE
Example code for plotting uses period_start when DataFrame uses t_start

### ISSUE THREAD

**Issue by simon-anz** [aguinane/nem-reader#32]
From https://nem-reader.readthedocs.io/en/latest/quickstart.html#charting

```
df.set_index("period_start", inplace=True)
```

**Comment by simon-anz** [comment]
Once that is changed, it works nicely :)

![image](https://user-images.githubusercontent.com/69175652/190304524-1d0013e1-2fa2-42e2-8a9d-ffb8f4f3641f.png)

**Comment by aguinane** [comment]
Updated in docs.

**Comment by lyricnz** [comment]
You missed one @aguinane 
```
./docs/quickstart.md:| period_start        | period_end          | E1    | Q1    | quality_method |
```

**Comment by aguinane** [comment]
Should be all fixed now.
