### ISSUE TITLE
Multi-CSV Zips?

### ISSUE THREAD

**Issue by mdavis-xyz** [aguinane/nem-reader#37]
While looking through the code to improve performance, I noticed this section:

https://github.com/aguinane/nem-reader/blob/master/nemreader/nem_reader.py#L88-L103

```
            with zipfile.ZipFile(self.file_path, "r") as archive:
                for csv_file in archive.namelist():
                    with archive.open(csv_file) as csv_text:
                        # Zip file is open in binary mode
                        # So decode then convert back to list
                        nmi_file = csv_text.read().decode("utf-8").splitlines()
                        reads = self.parse_nem_file(nmi_file, file_name=csv_file)
                        for nmi in reads.transactions.keys():
                            self.nmis.add(nmi)
                            suffixes = list(reads.transactions[nmi].keys())
                            self.nmi_channels[nmi] = suffixes
                        return NEMData(
                            header=self.header,
                            readings=reads.readings,
                            transactions=reads.transactions,
                        )
```

The `return` is inside the `for` loop. So if there's more than 1 CSV in the zip, it will be ignored.

Do these files ever have more than 1 file inside the zip?
If so, we should unindent the `return` statement (which requires concatenating other fields).

Or if we never expect more than one file in a zip, we should assert that the zip contents length is exactly 1.

**Comment by aguinane** [comment]
There should only be one file in the zip. I guess it wouldn't hurt to do a check though and throw a error if there are more.

**Comment by aguinane** [comment]
Check added in [a196911](https://github.com/aguinane/nem-reader/commit/a196911555a2e7e1c9c054d8bcc522d779af014a)
