### ISSUE TITLE
Nmi with multiple meters, do not return the meter number.

### ISSUE THREAD

**Issue by pantlavanya** [aguinane/nem-reader#9]
Is there a way to get meter for individual row for meters?

For Example: If data is coming for 3 meter which are associated to single NMI. It just return only 1 row without meter number.

**Comment by aguinane** [comment]
It will return the data for all three meters grouped by channel (which will be different for each meter). But the serial number of the meter doesn’t get added to the row.

**Comment by pantlavanya** [comment]
Hi Alex, 
Thanks for your reply. I have find a way to achieve this.
After modifying some of the files, I am able to get serial number. 

Can I send a PR for this?

**Comment by aguinane** [comment]
Yep send through and ill have a look

**Comment by pantlavanya** [comment]
Hi Alex,

Please find PR :- https://github.com/aguinane/nem-reader/pull/11

I have make support for NEM12, NEM13.

**Comment by pantlavanya** [comment]
This feature is added and the request is been merged
Thanks Alex.

**Comment by pantlavanya** [comment]
Hi Alex,
Hope your doing good.
You have merge the branch to develop,
It is possible it to sink develop with master?

**Comment by aguinane** [comment]
I've pushed a new version to pypi

**Comment by pantlavanya** [comment]
Thanks Alex.
